from pathlib import Path

from cubio.types import RasterioProfile
import rasterio as rio  # type: ignore
import numpy as np
import shutil

from .cube_context import CubeContext
from .envi_hdr_tools import (
    replace_shape_fields,
    replace_hdr_band_names,
    replace_hdr_description,
    extract_hdr_wavelength_units,
    extract_hdr_wavelengths,
    extract_hdr_bbl,
)


class EnviHeaderWriter:
    """Handles ENVI header file writing from a CubeContext object."""

    def __init__(self, cube_context: CubeContext) -> None:
        self.cc = cube_context

    def _validate_savefp(
        self, dst_fp: Path | str, use_image_name: bool
    ) -> Path:
        """Validates save path for HDR file."""
        savefp = Path(dst_fp)

        # Adding suffix based on the use_image_name option.
        if use_image_name:
            if savefp.is_dir():
                savefp = Path(savefp, self.cc.data_filename).with_suffix(
                    ".hdr"
                )
            else:
                savefp = savefp.with_name(
                    str(self.cc.data_filename)
                ).with_suffix(".hdr")
        else:
            savefp = savefp.with_suffix(".hdr")

        return savefp

    def _make_blank_envi_profile(self) -> RasterioProfile:
        """Makes a ENVI profile template, to be modified."""
        # Need a rasterio profile to do a proper write.
        envi_profile: RasterioProfile = {
            "driver": "ENVI",
            "width": 1,
            "height": 1,
            "count": 1,
            "dtype": self.cc.data_type,
            "crs": self.cc.crs,
            "transform": self.cc.geotransform.toaffine(),
            "interleave": self.cc.interleave,
            "nodata": -999,
        }
        return envi_profile

    def _modify_autogen_hdr(self, autogen_hdr_fp: str | Path) -> None:
        # Modifying rasterio-written .hdr file.
        # These are existing fields.
        replace_shape_fields(
            autogen_hdr_fp,
            samples=self.cc.ncols,
            lines=self.cc.nrows,
            bands=self.cc.nbands,
        )
        replace_hdr_band_names(autogen_hdr_fp, self.cc.band_names)
        replace_hdr_description(autogen_hdr_fp, self.cc.description)

        with open(autogen_hdr_fp, "a+") as f:
            # These are all new fields.
            if (
                extract_hdr_wavelength_units(autogen_hdr_fp)
                == "Wavelength Units not found."
            ):
                f.write(f"wavelength units = {self.cc.measurement_units}\n")
            if (
                extract_hdr_wavelengths(autogen_hdr_fp)
                == "Wavelengths not found."
            ):
                f.write(
                    "wavelength = "
                    f"{{{",".join([str(i) for i in self.cc.measurement_values])}}}\n"  # noqa
                )
            if extract_hdr_bbl(autogen_hdr_fp) == "No BBL Found":
                f.write(
                    "bbl = "
                    f"{{{",".join([str(i) for i in self.cc.bad_bands])}}}\n"
                )

    def to_file(self, dst: Path | str, use_image_name: bool = True) -> None:
        """
        Writes the model to a properly formatted ENVI header file.

        Parameters
        ----------
        dst : Path | str | None, optional
            Destination file path, by default None.

        Notes
        -----
        The file suffix is set internally, so the dst file does not need to
        include one.
        """
        savefp = self._validate_savefp(dst, use_image_name)

        # Need a temporary image and hdr file to write to. These will be empty.
        temp_img = savefp.with_name(f"_{savefp.name}").with_suffix(".img")
        temp_hdr = temp_img.with_suffix(".hdr")

        envi_profile = self._make_blank_envi_profile()

        # A blank image write is needed. We just use the .hdr file.
        with rio.open(temp_img, "w", **envi_profile) as f:
            f.write(np.empty((1, 1, 1)))

        temp_img.unlink()  # Discarding temporary image.
        if temp_img.with_suffix(".img.aux.xml").exists():  # Discarding xml
            temp_img.with_suffix(".img.aux.xml").unlink()

        # Modifying autogenerated hdr file.
        self._modify_autogen_hdr(temp_hdr)

        # Renaming the temporary hdr that was created with the temp image.
        shutil.move(temp_hdr, temp_hdr.with_name(temp_hdr.name[1:]))

        # Writing out the pydantic model in json form for easy reading.
        self.cc.write_json(savefp)
